name: Publish

on:
  push:
    branches:
    - master
    tags:
    - "!*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm run build --if-present
        npm test
        # npm run publish
    - name: prepare-to-publish-github-action
      run:
        npm prune --production
        sed "s/node_modules/# node_modules/g" .gitignore | tee .gitignore
    - uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: Publishing as Github Action
        branch: releases/v1
        file_pattern: node_modules/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
